### ISSUE TITLE
Issue with the --exclude-test-files flag?

### ISSUE THREAD

**Issue by devoncarew** [block-forest/dart-coveralls#14]
When I run with --exclude-test-files, I see:

```
Caught Exception: Unprocessable Entity
{"message":"JSON file not found or failed to parse.","error":true,"url":""}
Unhandled exception:
Uncaught Error: Exception: Unprocessable Entity
{"message":"JSON file not found or failed to parse.","error":true,"url":""}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:886)
#1      _asyncRunCallbackLoop (dart:async/schedule_microtask.dart:41)
#2      _asyncRunCallback (dart:async/schedule_microtask.dart:48)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:84)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:131)
```

Two other odd things:

Even with this exception, my coverage is generated and uploaded to coveralls; it (correctly) does not include coverage for the code in test/.

And, it looks like my tests are being executed twice, once before the exception is printed out and once after (https://travis-ci.org/dart-lang/usage/builds/45565957). I don't see the exception if I run w/o this flag. Note, in the build log above, the tests are executed three times - the first is me validating the build, and the next run(s) are to gather coverage.

**Comment by nilsdoehring** [comment]
Closing this because the issues reported did not occur during our efforts to get coveralls to 0.5.0. Feel free to file a new issue if you encounter any problems.
