### ISSUE TITLE
Fails to upload to coveralls

### ISSUE THREAD

**Issue by drager** [block-forest/dart-coveralls#41]
Get's error: `Exception: Unprocessable Entity
{"message":"JSON file not found or failed to parse.","error":true,"url":""}` when trying to upload data to coveralls. Check log output for more information: https://travis-ci.org/drager/faker/jobs/64918482

**Comment by donny-dont** [comment]
Hitting the same issue. Going back to 0.2.0 and things work fine.

**Comment by chinmaygarde** [comment]
Hitting the same issue too: https://travis-ci.org/domokit/cassowary/builds/68539740#L835

**Comment by eseidelGoogle** [comment]
0.5.0 was released this morning.  Please try again.  Things should work with the latest dart now.  Please let us know if you have any trouble!

**Comment by nilsdoehring** [comment]
Please file a new issue and analysis if this problems persists.
