### ISSUE TITLE
Use CI_* environment variables over git when available

### ISSUE THREAD

**Issue by donny-dont** [block-forest/dart-coveralls#45]
From https://coveralls.zendesk.com/hc/en-us/articles/201347419-Coveralls-currently-supports

> It's easy to support Coveralls on your CI server, all that's needed are these environment variables to be available at build time:

```
CI_NAME
CI_BUILD_NUMBER
CI_BUILD_URL
CI_BRANCH
CI_PULL_REQUEST (optional)
```

I'm trying to hook in the latest Drone to use coveralls but the git commands dart-coveralls is using fail so would it be possible to look for these environment variables before invoking git?

**Comment by eseidelGoogle** [comment]
The API reference is here:
https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference

There are some travis-specific mappings here:
https://github.com/block-forest/dart-coveralls/blob/master/lib/src/services/travis.dart

CI_BRANCH is wired up:
https://github.com/block-forest/dart-coveralls/blob/master/lib/src/git_data.dart#L132

You can see what we currently send here:
https://github.com/block-forest/dart-coveralls/blob/master/lib/src/coveralls_entities.dart#L258

So I guess what remains to resolve this bug would be to support these environment variable aliases in addition to the travis-specific ones?

**Comment by donny-dont** [comment]
Yep that would work. I'm no longer in a situation to test as I gave up on Coveralls. Switched over to https://aircover.co

**Comment by nilsdoehring** [comment]
I'll close this for now. Will revisit if there's demand.
