### ISSUE TITLE
dart.exe crashes

### ISSUE THREAD

**Issue by frankpepermans** [block-forest/dart-coveralls#48]
Getting this exception when running coveralls on my package:

https://github.com/frankpepermans/rxdart/blob/master/.travis.yml

Exception
ProcessException: There was a critical error. Exit code: -1073741819
  Command: dart --coverage_dir=C:\Users\Frank\AppData\Local\Temp\dart_coveralls.
97c45ac5-7a3c-11e5-beb9-7054d220a8f2 --package-root=E:\work\production\igindo\da
rt\rxdart\packages E:\work\production\igindo\dart\rxdart\test/all_tests.dart
package:dart_coveralls/src/collect_lcov.dart 116  LcovCollector._getCoverageJson
.<async>
===== asynchronous gap ===========================
dart:async                                        _Completer.completeError
package:dart_coveralls/src/collect_lcov.dart 124  LcovCollector._getCoverageJson
.<async>
===== asynchronous gap ===========================
dart:async                                        _Future.then
package:dart_coveralls/src/collect_lcov.dart 110  LcovCollector._getCoverageJson
.<async>
===== asynchronous gap ===========================
dart:async                                        Future.Future.microtask
package:dart_coveralls/src/collect_lcov.dart      LcovCollector._getCoverageJson

package:dart_coveralls/src/collect_lcov.dart 89   LcovCollector.getLcovInformati
on.<async>
===== asynchronous gap ===========================
dart:async                                        _Future.then
package:dart_coveralls/src/collect_lcov.dart 87   LcovCollector.getLcovInformati
on.<async>
===== asynchronous gap ===========================
dart:async                                        Future.Future.microtask
package:dart_coveralls/src/collect_lcov.dart      LcovCollector.getLcovInformati
on
package:dart_coveralls/src/cli_client.dart 39     CommandLineClient.getLcovResul
t
package:dart_coveralls/src/cli_client.dart 61     CommandLineClient.reportToCove
ralls.<async>
===== asynchronous gap ===========================
dart:async                                        Future.Future.microtask
package:dart_coveralls/src/cli_client.dart        CommandLineClient.reportToCove
ralls
http://localhost:59221/src/report.dart 81         ReportPart.execute.<async>.<fn

> .<async>
> ===== asynchronous gap ===========================
> package:stack_trace                               Chain.capture
> http://localhost:59221/src/report.dart 77         ReportPart.execute.<async>

**Comment by eseidelGoogle** [comment]
I'm not sure what to do with this? :)  This is a year and a half old now, so I think we can close this?

Please file a new issue if you're still seeing any trouble!  0.5.0 was just published today and should work with the latest dart.

**Comment by eseidelGoogle** [comment]
@nilsdoehring can you close, I don't see to have permissions. :)
