### ISSUE TITLE
dart-coveralls requires packages/ directory rather than supporting .packages

### ISSUE THREAD

**Issue by Hixie** [block-forest/dart-coveralls#53]
We'd love to use dart-coveralls in Flutter land, but we only support `.packages` these days, and this seems incompatible with dart-coveralls.

**Comment by Adracus** [comment]
Provide a tested PR and it'll be merged.

**Comment by eseidel** [comment]
i believe the modern way to do this is with the package_config package.  It has various apis including one which will handle both package/ and .packages cases (and even finding those directories):
https://github.com/dart-lang/package_config/blob/master/lib/discovery.dart#L93

**Comment by eseidel** [comment]
So I've written https://github.com/eseidel/dart-coveralls/tree/packages_file, but I think things are otherwise broken and need to be fixed before that will help.  When I run `dart_coveralls calc` I now get:
```
% dart bin/dart_coveralls.dart calc test/test_all.dart                                                            [/src/dart-coveralls]

Process exited with code 255.
Unrecognized flags: coverage_dir
```

**Comment by eseidel** [comment]
Oh.  I'm sad to have not noticed someone else wrote this. :D   Oh well.  Even better!

**Comment by eseidelGoogle** [comment]
This was fixed by https://github.com/block-forest/dart-coveralls/pull/59.

**Comment by eseidelGoogle** [comment]
0.5.0 Fixes, just published.
