### ISSUE TITLE
Ability to use dart-coveralls with a provided .json file

### ISSUE THREAD

**Issue by Hixie** [block-forest/dart-coveralls#54]
In Flutter land, we run tests in esoteric configurations: we have our own VM embedding, we sometimes run the tests on devices, it's a complicated setup.

However, we can set things up so that we get a bunch of JSON files generated from various runs of the VM over various tests in various configurations.

We'd like to use dart-coveralls (or something else?) to convert these JSON files into useful data so we can tell where we need more testing.

**Comment by Adracus** [comment]
You might have a look at #42

**Comment by Hixie** [comment]
That's more about uploading a report once you have one. I want to generate the report from the raw VM data.

**Comment by Adracus** [comment]
Ok if that is the case you are free to provide a tested PR and it'll be merged.

**Comment by eseidelGoogle** [comment]
I believe that `dart-coveralls upload` does exactly this?  If it doesn't, I'm happy to fix it.
