### ISSUE TITLE
Starting Dart 1.16.0, dart_coverage is failing

### ISSUE THREAD

**Issue by sestegra** [block-forest/dart-coveralls#55]
The way of computing coverage information has changed in Dart 1.16.0.
As a result, dart_coveralls is failing with following error.

```
$ pub global run dart_coveralls calc test/serializer_test.dart
Process exited with code 255.
Unrecognized flags: coverage_dir
```

**Comment by lejard-h** [comment]
Same on 1.17.1

**Comment by cedx** [comment]
Same on 1.21.0 :(

**Comment by eseidelGoogle** [comment]
0.5.0 was released this morning which is known to work with 1.22 and 1.23 at least. The SDK constraint is now set to 1.16.0+.  I suspect this is resolved.

**Comment by nilsdoehring** [comment]
What @eseidelGoogle said. Please file a new issue if you encounter problems with a specific version.
