### ISSUE TITLE
Update pubspec.yaml constraints before 0.5.0 release?

### ISSUE THREAD

**Issue by eseidelGoogle** [block-forest/dart-coveralls#65]
I believe we need to update:

- [ ] minimum SDK version to 1.20+?  Maybe 1.21 or 1.22?
- [ ] minimum coverage revision to 0.9.0+?  Maybe even 0.9.2+?

@nilsdoehring.  Let me know, and then I'm happy to push the publish button to work around https://github.com/dart-lang/pub/issues/1442

**Comment by nilsdoehring** [comment]
Thanks! I have yet to master the art of thinking of everything before pushing / publishing, hehe. Does maintaining 60k LOC layered into a dozen packages count as an excuse?

SDK version: I think we can go lower, can't we? How about using the SDK constraints that coverage has? '>=1.16.0 <2.0.0'
Coverage revision: Going for newest shouldn't hurt, so 0.9.2+

**Comment by eseidelGoogle** [comment]
Sounds plausible.  coverage uses 1.16+ too:
https://github.com/dart-lang/coverage/blob/master/pubspec.yaml#L7
