### ISSUE TITLE
Getting ready for Dart2 (package updates:`file` and `mockito`).

### ISSUE THREAD

**Issue by pq** [block-forest/dart-coveralls#76]
I started playing with running `dart_coveralls` in preview Dart2 mode and hit a snag because it's filesystem abstraction (`mockable_filesystem`) isn't Dart2-friendly.  While `mockable_filesystem` *could* be updated, I think a better option is to migrate to the [`file` package ](https://pub.dartlang.org/packages/file), which is under active development.

FWIW, I started down this road in #75 which needs some attention --- minimally in getting the tests working.  Comments and thoughts on that or the direction altogether are most welcome!

/cc @kevmoo @tvolkert @nilsdoehring

FYI @devoncarew

**Comment by pq** [comment]
FWIW: I elected to move forward to `mockito` (in favor of the long-in-the-tooth `mock`) and have the tests mostly passing.  Note that it does not run on STABLE (but I wouldn't expect it to?)

**Comment by pq** [comment]
Updated the title as this is really about Dart2 readiness.

**Comment by bkonyi** [comment]
@pq would you happen to know when to expect the 0.6.0 release to be published?

**Comment by pq** [comment]
hey @bkonyi !  I'm not an uploader but I think it's good to go...

pinging @nilsdoehring @kevmoo @Adracus @eseidelGoogle who are 👍 

(Alternatively, if I get made one, I'm happy to do it too!)

**Comment by nilsdoehring** [comment]
@bkonyi published it just now
@pq couldn't find your email to make you an uploader

**Comment by kevmoo** [comment]
Thanks!

**Comment by pq** [comment]
Thanks @nilsdoehring !

I just mailed you from a good address.

Closing this one out as we should now be good to go! 🤞
